### ISSUE TITLE
[feature request] nested array

### ISSUE THREAD

**Issue by xNok** [gagan-bansal/json-groupby#3]
This library is very useful and the syntax make it easy to understand (very close to pandas a Python data manipulation library). However I see a missing feature that concern recurring use case .

Given the example of a book store, I retrieve the list of books with their title and the list of their authors.

```JSON
  {
    "title": "",
    "author": [
      {
        "given": "",
        "family": "",
        "affiliation": []
      },
      {
        "given": "",
        "family": "",
        "affiliation": []
      },
]
```

Then I want to group those books by authors. (This append a lot when you have entities with a relation where books asMany authors.

Your library could implement a SQL like syntax to specify on which property inside the array you want to group

```js
groupBy(books, ['author.given'])
```
One solution to tackle this would be to add a temporary array `tmp` that contain the property `given` for each `author` then use the group by as for `tags`

```js
  books.forEach(function(item) {
      item.tmp = item['authors'].map(function(x) {
         return x.['given'];
      })
  });

groupBy(books, ['tmp'])
```

I believe this feature will complete the coverage of this library in terms of grouping and manipulating JSON Objects

**Comment by gagan-bansal** [comment]
@xNok Nice suggestion, I'll implement this on coming weekend.

**Comment by gagan-bansal** [comment]
@xNok Can you please give the sample input json (properties having values) and desired output.

**Comment by gagan-bansal** [comment]
This feature is added in this [commit](https://github.com/gagan-bansal/json-groupby/commit/6cb69a0)
